"""Assemble the deliverables: annotated frames, report.json, and a draft MBIS report.

This is the surface the dashboard reads and the RI signs. Everything here is a
DRAFT — the Registered Inspector verifies and signs; by law the final legal
determination is theirs (jury Q&A T8). We produce the evidence and a draft mapped
to the official MBIS categories, never the final call.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import cv2

# Severity palette (BGR) — muted, Palantir-style; matches the Facadia dashboard.
SEV_BGR = {1: (141, 122, 107), 2: (142, 157, 74), 3: (62, 154, 199),
           4: (59, 115, 210), 5: (75, 69, 208)}
SEV_LABEL = {1: "Cosmetic", 2: "Minor", 3: "Moderate", 4: "Serious", 5: "Critical"}
MBIS_LABEL = {"external_walls": "External Walls", "projections": "Projections",
              "signboards": "Signboards", "common_parts": "Common Parts"}


def _corner_brackets(img, x, y, w, h, color, t=2):
    """Precise L-brackets at the four corners (a clean detection marker)."""
    L = int(max(12, min(40, min(w, h) * 0.22)))
    for cx, cy, sx, sy in ((x, y, 1, 1), (x + w, y, -1, 1),
                           (x, y + h, 1, -1), (x + w, y + h, -1, -1)):
        cv2.line(img, (cx, cy), (cx + sx * L, cy), color, t, cv2.LINE_AA)
        cv2.line(img, (cx, cy), (cx, cy + sy * L), color, t, cv2.LINE_AA)


def annotate_frames(defects: list[dict], out_dir: str) -> dict[str, str]:
    """Mark each defect with a clean detection box + label chip on its frame.

    Faint bounding box + crisp corner brackets + a compact dark readout chip with a
    coloured severity bar — restrained, not glowy, matching the Facadia dashboard.
    Returns {frame_name: annotated_image_path}.
    """
    out = Path(out_dir) / "annotated"
    out.mkdir(parents=True, exist_ok=True)

    by_frame: dict[str, list[dict]] = defaultdict(list)
    for d in defects:
        by_frame[d["frame"]].append(d)

    result: dict[str, str] = {}
    for frame_path, ds in by_frame.items():
        img = cv2.imread(frame_path)
        if img is None:
            continue
        H, W = img.shape[:2]

        for d in ds:
            x, y, w, h = d["bbox"]
            color = SEV_BGR[d["severity"]]
            # faint full box, then crisp corner brackets on top
            box = img.copy()
            cv2.rectangle(box, (x, y), (x + w, y + h), color, 1, cv2.LINE_AA)
            cv2.addWeighted(box, 0.45, img, 0.55, 0, img)
            _corner_brackets(img, x, y, w, h, color, 2)

            sev = d["severity"]
            m = d["measurement"]
            size = (f'{m["width_mm"]} mm' if m.get("width_mm") is not None
                    else f'{m.get("area_mm2")} mm2')
            # ASCII only — Hershey fonts can't render middots/emoji.
            lines = [f'{d["id"]}   {d["defect_type"].upper()}',
                     f'SEV-{sev} {SEV_LABEL[sev].upper()}    {size}'
                     + ('    REFER RI' if d.get("ri_flag") else '')]
            tw = max(cv2.getTextSize(l, cv2.FONT_HERSHEY_SIMPLEX, 0.46, 1)[0][0] for l in lines)
            pw, ph = min(tw + 20, W), 40
            px = max(0, min(x, W - pw))
            py = y - ph - 7 if y - ph - 7 >= 0 else min(y + h + 7, H - ph)
            py = max(0, py)
            region = img[py:py + ph, px:px + pw]
            chip = region.copy(); chip[:] = (17, 14, 12)
            cv2.addWeighted(chip, 0.80, region, 0.20, 0, region)
            cv2.line(img, (px, py), (px, py + ph), color, 3, cv2.LINE_AA)  # severity bar
            for i, l in enumerate(lines):
                cv2.putText(img, l, (px + 11, py + 16 + i * 17),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.46, (232, 236, 242), 1, cv2.LINE_AA)

        dest = out / f"{Path(frame_path).stem}_annotated.jpg"
        cv2.imwrite(str(dest), img, [cv2.IMWRITE_JPEG_QUALITY, 92])
        result[Path(frame_path).stem] = str(dest)
    return result


def build_report(building: dict, defects: list[dict], health: dict,
                 annotated: dict[str, str]) -> dict:
    """The machine-readable report.json the dashboard renders."""
    return {
        "building": building,
        "health": health,
        "defects": [
            {**d, "annotated": annotated.get(d["frame_name"], d["frame"])}
            for d in defects
        ],
        "disclaimer": "DRAFT — generated by the Facadia AI surveyor. Pending Registered "
                      "Inspector (RI) verification and sign-off. Not a legal "
                      "determination.",
    }


def write_markdown(report: dict) -> str:
    """A draft MBIS-style inspection report, defects grouped by statutory category."""
    b, h = report["building"], report["health"]
    L = [
        f"# Facade Inspection Report (DRAFT) — {b.get('name', 'Subject Building')}",
        "",
        f"> {report['disclaimer']}",
        "",
        "## 1. Summary",
        "",
        f"- **Inspection date:** {b.get('inspection_date', '—')}",
        f"- **Source footage:** {b.get('footage', '—')}",
        f"- **Standoff / GSD:** {b.get('standoff_m', '—')} m  ·  "
        f"{b.get('gsd_mm_per_px', '—')} mm/px",
        f"- **Building-health score:** **{h['score']}/100** ({h['band']})",
        f"- **Defects found:** {h['n_defects']}  ·  worst severity: "
        f"{h['worst_severity']}  ·  flagged for RI: {h['ri_flags']}",
        "",
        "## 2. Defect schedule",
        "",
        "| ID | Category | Type | Sev | Width (mm) | Conf | RI? | Action |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for d in report["defects"]:
        L.append(
            f"| {d['id']} | {MBIS_LABEL.get(d['mbis_category'], d['mbis_category'])} "
            f"| {d['defect_type']} | {d['severity']} ({SEV_LABEL[d['severity']]}) "
            f"| {d['measurement'].get('width_mm')} | {d['confidence']:.2f} "
            f"| {'⚠️ yes' if d['ri_flag'] else 'no'} | {d['recommended_action']} |"
        )

    # 3. Findings grouped by MBIS statutory category.
    L += ["", "## 3. Findings by statutory category", ""]
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for d in report["defects"]:
        by_cat[d["mbis_category"]].append(d)
    for cat, ds in by_cat.items():
        L.append(f"### {MBIS_LABEL.get(cat, cat)}")
        L.append("")
        for d in ds:
            flag = "  **[Refer to RI — detailed investigation may be required]**" if d["ri_flag"] else ""
            L.append(f"**{d['id']} — {d['defect_type']} (Severity {d['severity']}, "
                     f"{SEV_LABEL[d['severity']]}){flag}**")
            L.append("")
            L.append(f"{d['report_text']}")
            L.append("")
            L.append(f"*Likely cause:* {d['cause']}  ·  *Rubric anchor:* {d['rubric_anchor']}")
            L.append("")

    L += ["## 4. Sign-off", "",
          "_Generated by Facadia. The Registered Inspector must verify each finding "
          "against the evidence and amend severities as their professional judgment "
          "requires before signing._", "",
          "Registered Inspector: ________________________   Date: ____________", ""]
    return "\n".join(L)


def write_all(report: dict, out_dir: str) -> tuple[str, str]:
    """Write report.json + report.md into out_dir; return their paths."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    jpath = out / "report.json"
    mpath = out / "report.md"
    jpath.write_text(json.dumps(report, indent=2))
    mpath.write_text(write_markdown(report))
    return str(jpath), str(mpath)
