"""Assemble the deliverables: annotated frames, report.json, and a draft MBIS report.

This is the surface the dashboard reads and the RI signs. Everything here is a
DRAFT — the Registered Inspector verifies and signs; by law the final legal
determination is theirs (jury Q&A T8). We produce the evidence and a draft mapped
to the official MBIS categories, never the final call.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import cv2

# Severity -> BGR colour for annotation (green -> red as severity climbs).
SEV_BGR = {1: (90, 170, 90), 2: (60, 200, 220), 3: (40, 150, 245),
           4: (40, 90, 240), 5: (40, 40, 230)}
SEV_LABEL = {1: "Cosmetic", 2: "Minor", 3: "Moderate", 4: "Serious", 5: "Critical"}
MBIS_LABEL = {"external_walls": "External Walls", "projections": "Projections",
              "signboards": "Signboards", "common_parts": "Common Parts"}


def annotate_frames(defects: list[dict], out_dir: str) -> dict[str, str]:
    """Draw each defect's box + severity label on its source frame.

    Returns {frame_name: annotated_image_path}. Multiple defects on one frame are
    drawn on the same image.
    """
    out = Path(out_dir) / "annotated"
    out.mkdir(parents=True, exist_ok=True)

    by_frame: dict[str, list[dict]] = defaultdict(list)
    for d in defects:
        by_frame[d["frame"]].append(d)

    result: dict[str, str] = {}
    for frame_path, ds in by_frame.items():
        img = cv2.imread(frame_path)
        if img is None:
            continue
        for d in ds:
            x, y, w, h = d["bbox"]
            color = SEV_BGR[d["severity"]]
            cv2.rectangle(img, (x, y), (x + w, y + h), color, 3)
            tag = f'{d["id"]}  S{d["severity"]} {d["defect_type"]}  {d["measurement"].get("width_mm")}mm'
            (tw, th), _ = cv2.getTextSize(tag, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
            ly = max(0, y - th - 8)
            cv2.rectangle(img, (x, ly), (x + tw + 8, ly + th + 8), color, -1)
            cv2.putText(img, tag, (x + 4, ly + th + 2),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)
        dest = out / f"{Path(frame_path).stem}_annotated.jpg"
        cv2.imwrite(str(dest), img, [cv2.IMWRITE_JPEG_QUALITY, 90])
        result[Path(frame_path).stem] = str(dest)
    return result


def build_report(building: dict, defects: list[dict], health: dict,
                 annotated: dict[str, str]) -> dict:
    """The machine-readable report.json the dashboard renders."""
    return {
        "building": building,
        "health": health,
        "defects": [
            {**d, "annotated": annotated.get(d["frame_name"], d["frame"])}
            for d in defects
        ],
        "disclaimer": "DRAFT — generated by Hawkeye AI surveyor. Pending Registered "
                      "Inspector (RI) verification and sign-off. Not a legal "
                      "determination.",
    }


def write_markdown(report: dict) -> str:
    """A draft MBIS-style inspection report, defects grouped by statutory category."""
    b, h = report["building"], report["health"]
    L = [
        f"# Facade Inspection Report (DRAFT) — {b.get('name', 'Subject Building')}",
        "",
        f"> {report['disclaimer']}",
        "",
        "## 1. Summary",
        "",
        f"- **Inspection date:** {b.get('inspection_date', '—')}",
        f"- **Source footage:** {b.get('footage', '—')}",
        f"- **Standoff / GSD:** {b.get('standoff_m', '—')} m  ·  "
        f"{b.get('gsd_mm_per_px', '—')} mm/px",
        f"- **Building-health score:** **{h['score']}/100** ({h['band']})",
        f"- **Defects found:** {h['n_defects']}  ·  worst severity: "
        f"{h['worst_severity']}  ·  flagged for RI: {h['ri_flags']}",
        "",
        "## 2. Defect schedule",
        "",
        "| ID | Category | Type | Sev | Width (mm) | Conf | RI? | Action |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for d in report["defects"]:
        L.append(
            f"| {d['id']} | {MBIS_LABEL.get(d['mbis_category'], d['mbis_category'])} "
            f"| {d['defect_type']} | {d['severity']} ({SEV_LABEL[d['severity']]}) "
            f"| {d['measurement'].get('width_mm')} | {d['confidence']:.2f} "
            f"| {'⚠️ yes' if d['ri_flag'] else 'no'} | {d['recommended_action']} |"
        )

    # 3. Findings grouped by MBIS statutory category.
    L += ["", "## 3. Findings by statutory category", ""]
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for d in report["defects"]:
        by_cat[d["mbis_category"]].append(d)
    for cat, ds in by_cat.items():
        L.append(f"### {MBIS_LABEL.get(cat, cat)}")
        L.append("")
        for d in ds:
            flag = "  **[Refer to RI — detailed investigation may be required]**" if d["ri_flag"] else ""
            L.append(f"**{d['id']} — {d['defect_type']} (Severity {d['severity']}, "
                     f"{SEV_LABEL[d['severity']]}){flag}**")
            L.append("")
            L.append(f"{d['report_text']}")
            L.append("")
            L.append(f"*Likely cause:* {d['cause']}  ·  *Rubric anchor:* {d['rubric_anchor']}")
            L.append("")

    L += ["## 4. Sign-off", "",
          "_Generated by Hawkeye. The Registered Inspector must verify each finding "
          "against the evidence and amend severities as their professional judgment "
          "requires before signing._", "",
          "Registered Inspector: ________________________   Date: ____________", ""]
    return "\n".join(L)


def write_all(report: dict, out_dir: str) -> tuple[str, str]:
    """Write report.json + report.md into out_dir; return their paths."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    jpath = out / "report.json"
    mpath = out / "report.md"
    jpath.write_text(json.dumps(report, indent=2))
    mpath.write_text(write_markdown(report))
    return str(jpath), str(mpath)
